---
title: "Project1 - Model Linear"
author: "Fauzan Adzhima Alamsyah"
date: "2024-09-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=TRUE,

tidy.opts=list(width.cutoff=60),
tidy=TRUE)

options(scipen = 9999)
rm(list=ls())
```

```{r}
library(dplyr)
library(leaps)
library(GGally)
library(MASS)
library(lmtest)
library(caTools)
```

```{r}
students <- read.csv("data_input/StudentPerformanceFactors.csv")
hist(students$Exam_Score, breaks=20)
hist(students$Hours_Studied)
```
```{r}
students
```
```{r}
students_new <- slice(students,1:200)
summary(students_new[c("Hours_Studied","Exam_Score")])
```

```{r}
set.seed(123)
split <- sample.split(students_new$Exam_Score, SplitRatio = 0.8)
students_train <- subset(students_new, split == TRUE)
students_test <- subset(students_new, split == FALSE)
```

```{r}
max(students_train$Hours_Studied)
students_test
```

domain variabel prediktor = [4,36]

## model data 80% pertama

```{r}
regressor <- lm(formula = Exam_Score ~ Hours_Studied , data = students_train)
summary(regressor)
```


```{r}
y_pred <- predict(regressor, newdata = students_test)
y_pred
```
```{r}
new_data <- data.frame(Hours_Studied = c(11,17))
predictions <- predict(regressor, newdata = new_data)
predictions
```

```{r}
data_test <- data.frame(Hours_Studied = c(11))
predict(regressor, newdata = data_test, interval = "prediction", level = 0.95)
```

```{r}
# Menghitung koefisien korelasi
correlation <- cor(students_train$Hours_Studied, students_train$Exam_Score)

# Menghitung standar deviasi dari Hours_Studied dan Exam_Score
std_hours <- sd(students_train$Hours_Studied)
std_exam <- sd(students_train$Exam_Score)

# Verifikasi kemiringan dengan koefisien korelasi
calculated_slope <- correlation * (std_exam / std_hours)

# Menampilkan hasil
cat("Standar Deviasi dari Hours_Studied:",std_hours,"\n")
cat("Standar Deviasi dari Exam_Score:",std_exam,"\n")
cat("Koefisien Korelasi (r):", correlation, "\n")
cat("Kemiringan Garis Regresi Berdasarkan Korelasi:", calculated_slope, "\n")
cat("Kemiringan Garis Regresi dari Model:", coef(regressor)[2], "\n")

```
```{r}
4.548*4.548
```

```{r}
set.seed(728)
split <- sample.split(students_new$Exam_Score, SplitRatio = 0.8)
data2 <- subset(students_new, split == TRUE)
#students_test <- subset(students_new, split == FALSE)
```

## model data 80% kedua

```{r}
regressor1 <- lm(formula = Exam_Score ~ Hours_Studied , data = data2)
summary(regressor1)
```


```{r}
0.27414 - 0.25625
```

## model data 200 lengkap

```{r}
regressor2 <- lm(formula = Exam_Score ~ Hours_Studied , data = students_new)
summary(regressor2)
```

```{r}
# Scatter Plot 
plot(students_train$Hours_Studied,
     students_train$Exam_Score,
     xlab = "Hours_Studied",
     ylab = "Exam_Score",
     main = "Plot Regresi Exam_Score ~ Hours_Studied", pch = 20)

# Garis Regresi
abline(regressor,
       col = "red",
       lwd = 2)

legend("bottomright",
       legend = "Garis Regresi",
       col = "blue",
       lwd = 2,
       bty = "n")

```


```{r}
head(regressor$residual)
head(resid(regressor))
plot(regressor$residual)
plot(regressor, 1)
hist(regressor$residual)
```


```{r}
predict(regressor, newdata = data.frame(Hours_Studied = c(11)), interval = "confidence", level = 0.95)

```


```{r}

# Ambil residuals
residuals <- regressor$residuals

# Hitung variansi residuals
error_variance <- var(residuals)

# Cetak variansi error
print(error_variance)

```


```{r}
# Mengambil MSE dari ringkasan model
mse <- summary(regressor)$sigma^2
cat("Variansi Error (σ²):", mse, "\n")

```


```{r}
# Mengambil standard error untuk koefisien hp
se_hp <- summary(regressor)$coefficients["Hours_Studied", "Std. Error"]

# Menghitung variansi
variance_hp <- se_hp^2

cat("Variansi koefisien Hours_Studied (dari Std. Error):", variance_hp, "\n")

```
